0.90.10: move pw99/pdt vapps to winston99/winstonpress
Runs donjon/winston-migrate.sh once. Old ink names stay aliases.

diff --git a/update b/update
--- a/update
+++ b/update
@@ -797,6 +797,41 @@ fi
 ###############END#UPGRADE#PATCH#
 
 
+upgradePatchVerno=0.90.10
+if [ $(/usr/bin/echo ${upgradePatchVerno} | /usr/bin/sed -e "s/\.//g" | /usr/bin/sed -e "s/^0*//g") -gt $(/usr/bin/echo ${Verno} | /usr/bin/sed -e "s/\.//g" | /usr/bin/sed -e "s/^0*//g") ] ; then
+cleanPatchVerno="$(/usr/bin/echo $upgradePatchVerno | /usr/bin/sed -e "s/\.//g")"
+PCLdoc="$(/usr/bin/cat <<UPCL
+Patch ${upgradePatchVerno} Changelog:
+- pw99 namespace is winston99 (vapps/winston99.DOMAIN, ink install winston99)
+- pdt-news namespace is winstonpress (vapps/winstonpress.DOMAIN, ink install winstonpress)
+- Moves existing /srv/www/vapps/pw99.* and pdt.* plus vapp configs
+- GitHub fetch: JesseSteele/Winston99 and JesseSteele/winstonpress
+- Old ink install pw99 / pdt remain aliases
+UPCL
+)"
+/usr/bin/echo "$PCLdoc"
+eval "v$cleanPatchVerno='$(/usr/bin/echo "$PCLdoc")'"
+
+if [ -d "/opt/verb/${vUpdateRepo}/${upgradePatchVerno}/" ]; then
+cd /opt/verb/${vUpdateRepo}/${upgradePatchVerno}/; fi
+
+###### SCRIPTS GO HERE #####
+if [ -x /opt/verb/donjon/winston-migrate.sh ]; then
+  /opt/verb/donjon/winston-migrate.sh || true
+else
+  /usr/bin/echo "winston-migrate.sh missing; skipped live vapp moves."
+fi
+
+###### END SCRIPTS #########
+/usr/bin/sed -i "s/Verno=.*/Verno=\"${upgradePatchVerno}\"/g" /opt/verb/conf/inklists/verberverno
+. /opt/verb/conf/inklists/verberverno
+/usr/bin/echo "Verber upgraded to v${Verno}"
+else
+/usr/bin/echo "${upgradePatchVerno} patch not necessary..."
+fi
+###############END#UPGRADE#PATCH#
+
+
 # Security check
 
 /opt/verb/serfs/setsecure; wait
