Bugs

diff --git a/serfs/inkget b/serfs/inkget
--- a/serfs/inkget
+++ b/serfs/inkget
@@ -18,35 +18,34 @@ APPNAME=$1
 . /opt/verb/conf/siteinkget
 
 if [ "${INKGET_REPO}" = "NOT_SET" ]; then
-/bin/echo "inkNet is not setup, so no repo is available. Can't download the necessary package."
-exit 8
-fi
+  /bin/echo "inkNet is not setup, so no repo is available. Can't download the necessary package."
+exit 8; fi
 
 # zjz
 if [ $INKGET_METHOD = "ZJZ" ]; then
-/opt/verb/donjon/repoupdate/${APPNAME}.updaterepo; wait
-## Check repo for failed DL
- if [ "$2" = "check" ] && [ -f "/opt/verb/donjon/repoupdate/${APPNAME}.failed" ]; then
- exit 4; fi
-## Continue
-/bin/cp /opt/verb/repo/${APPNAME}.vtxz .
-/bin/echo "Copied for install."
- if [ $INKGET_REPO = "TEMP" ]; then
-/bin/rm /opt/verb/repo/${APPNAME}.vtxz
-/bin/echo "Temp repo files cleaned-up."
- else
-/bin/echo "Repo files kept."
- fi
+  /opt/verb/donjon/repoupdate/${APPNAME}.updaterepo; wait
+  ## Check repo for failed DL
+  if [ "$2" = "check" ] && [ -f "/opt/verb/donjon/repoupdate/${APPNAME}.failed" ]; then
+  exit 4; fi
+  ## Continue
+  /bin/cp /opt/verb/repo/${APPNAME}.vtxz .
+  /bin/echo "Copied for install."
+  if [ $INKGET_REPO = "TEMP" ]; then
+    /bin/rm /opt/verb/repo/${APPNAME}.vtxz
+    /bin/echo "Temp repo files cleaned-up."
+  else
+    /bin/echo "Repo files kept."
+  fi
 fi
 
 # wget
 if [ $INKGET_METHOD = "USE_WGET" ]; then
-/usr/bin/wget https://${INKGET_REPO}/repo/${APPNAME}.vtxz --no-check-certificate
+  /usr/bin/wget https://${INKGET_REPO}/repo/${APPNAME}.vtxz --no-check-certificate
 fi
 
 # inker
 if [ $INKGET_METHOD = "INKER_CP" ]; then
-/bin/cp /opt/ink/repo/${APPNAME}.vtxz .
+  /bin/cp /opt/ink/repo/${APPNAME}.vtxz .
 fi
 
 ## DEV NOTE: Other secure methods are planned in the roadmap
@@ -57,6 +56,5 @@ fi
 
 # Exit if failed
 if [ ! -f ${APPNAME}.vtxz ]; then
-/bin/echo "Couldn't get the file! I quit."
+  /bin/echo "Couldn't get the file! I quit."
 exit 4; fi
-
diff --git a/serfs/installpfa b/serfs/installpfa
--- a/serfs/installpfa
+++ b/serfs/installpfa
@@ -15,7 +15,7 @@
 ## ./installpfa mysecretpath somepassword
 
 
-CVAPPNAME=postfixadmin
+CVAPPNAME="postfixadmin"
 # Include the config files
 . /opt/verb/conf/servertype
 . /opt/verb/conf/sitenameip
@@ -62,14 +62,15 @@ fi
 cd /srv/www/email
 /opt/verb/serfs/inkget ${CVAPPNAME} check; wait
 if [ "$?" = 4 ]; then
-/bin/echo "Repo failed to retrieve the file."
-exit 4; fi
+  /bin/echo "Repo failed to retrieve the file."
+  exit 4; fi
 if [ ! -f ${CVAPPNAME}.vtxz ]; then
-/bin/echo "Failed to retrieve from the repo."
-exit 4; fi
+  /bin/echo "Failed to retrieve from the repo."
+  exit 4; fi
 
 /bin/rm -rf ${CVAPPNAME}
 /opt/verb/serfs/vtxzout ${CVAPPNAME}; wait
+
 ## Fix a bug
 /bin/mkdir -p /srv/www/email/postfixadmin/templates_c
 
