Tweaks

diff --git a/serfs/inkget b/serfs/inkget
--- a/serfs/inkget
+++ b/serfs/inkget
@@ -45,16 +45,12 @@ if [ $INKGET_METHOD = "INKER_CP" ]; then
     /bin/echo "Temp repo files cleaned-up."
   else
     /bin/echo "Repo files kept."
+    # Exit if failed
+    if [ ! -f /opt/verb/repo/${APPNAME}.vtxz ]; then
+      /bin/echo "Couldn't get the file! I quit."
+    exit 4; fi
   fi
 fi
 
 ## DEV NOTE: Other secure methods are planned in the roadmap
 # SSH
-
-# SSL
-
-
-# Exit if failed
-if [ ! -f ${APPNAME}.vtxz ]; then
-  /bin/echo "Couldn't get the file! I quit."
-exit 4; fi
