Streamline inkget & repo methods, Nextcloud cleanup

diff --git a/serfs/installphpmyadmin b/serfs/installphpmyadmin
--- a/serfs/installphpmyadmin
+++ b/serfs/installphpmyadmin
@@ -14,25 +14,6 @@ if [ -z ${1} ]; then
 /bin/echo "You must designate a folder."
 exit 8; fi
 
-# Include the configs
-. /opt/verb/conf/sitenameip
-. /opt/verb/conf/siteurilist
-
-# Download and establish Drupal in the server to pre-created domain
-cd /srv/www/vapps
-/opt/verb/serfs/inkget ${CVAPPNAME}; wait
-### Check
-/opt/verb/serfs/inkget ${CVAPPNAME} check
-if [ "$?" = 4 ]; then
-/bin/echo "Repo failed to retrieve the file."
-exit 4; fi
-if [ ! -f ${CVAPPNAME}.vtxz ]; then
-/bin/echo "Failed to retrieve from the repo."
-exit 4; fi
-
-/bin/rm -rf ${CVAPPNAME}
-/opt/verb/serfs/vtxzout ${CVAPPNAME}; wait
-
 DIRECTRY=${1}
 
 # Auto database
@@ -40,6 +21,17 @@ if [ -z ${3} ]; then
 DBPASSWORD=$(/usr/bin/pwgen -c -1 20); fi
 if [ -z ${2} ]; then
 DBUSER=phpmy$(/usr/bin/pwgen -s -1 15); fi
+
+# Include the configs
+. /opt/verb/conf/sitenameip
+. /opt/verb/conf/siteurilist
+
+# Download and establish Drupal in the server to pre-created domain
+cd /srv/www/vapps
+/opt/verb/serfs/inkget ${CVAPPNAME} check; wait
+if [ "$?" = 4 ]; then
+/bin/echo "Repo failed to retrieve the file."
+exit 4; fi
 
 # Create the boss user
 /opt/verb/serfs/mysqlnewboss "${DBUSER}" "${DBPASSWORD}"
